### ISSUE TITLE
InitialCaption not works when is not a image fileinput

### ISSUE THREAD

**Issue by leandrogehlen** [kartik-v/yii2-widget-fileinput#26] opened 2015-04-12 13:16 UTC
When  the property `initialPreview` is not set, the `initialCaption` not works

**Comment by kartik-v** [comment] 2015-04-12 15:52
It was intended to be that way. Will record an enhancement for this.

**Comment by kartik-v** [comment] 2015-04-12 16:50
This will be resolved via kartik-v/bootstrap-fileinput#245.

**Closed by kartik-v** 2015-04-12 16:50 UTC
Labels: enhancement

**Comment by leandrogehlen** [comment] 2015-04-13 10:52
thanks
